server:
  port: 8083

spring:
  application:
    name: updater-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

elasticsearch:
  port: 9200
  host: localhost